### ISSUE TITLE
Maintain charges (master data) and charge price lists 

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1053]
## Problem Description

As a grid access provider or system operator
We want to be able to change, and stop, charges and charge price lists, 
so that updated prices can be included, and stopped charges excluded, from settlement 

As a grid access provider or system operator
We want to submit Charge master data and Charge Prices separately, using the same message type with different business reason codes, one for master data and one for prices 
So that the intention with the message is clear and message sizes are reduced. 

As a grid access provider or system operator
We want to be able to cancel a stop (within certain time limits)

### In scope:
* Inbound: CIM XML RSM-033 'Price list' messages 
* Outbound: CIM XML RSM-033 'Price list' messages for Grid Access Providers
* Charges data model must support updates and keeping the current state of a charge
* Publish integration events related to maintaining charges and prices.
* we want to change of current state of a charge, not a complete bitemporal historical model 

### Out of scope:
* A complete bitemporal historical data model (allowing audits)
* CIM JSON
* eBIX
* Outbound messages to Electricity Suppliers
* Maintain charge links due to stopping the underlying charge. Handled in another feature.
* Complete validation rule set. Subsequent feature will address the business requirements for validation. 
* Displaying charges in GUI. Charges and Charge Prices will only be possible to fetch through OData api.

<hr>

### Business notes

* Initial master data and prices were received in the same message, using one business reason code. This method has been adjusted, the message is enriched with a business reason code, which identifies whether the purpose is to maintain charges master data or price lists {D08 and D18 respectively}.

* The [Charges data model](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/data-models/ChargesDataModel.png ) contains `ChargePeriod`, which holds the master data fields possible to change in an `update`.
* Charge Master Data: We will allow charge update where no changes in master data appears. It will be processed as usual.
* Charge Prices: If only one hour is changed, then its perfectly acceptable to send in half a year of data.  
* Stopping a Charge is final - you cannot both change master data and stop a charge in the same request!
(This needs to be aligned and communicated with first level support)
 
<hr>

## Acceptance criteria 

- [x] (1a) Given a valid charge master update request is received
when storing it
then it is persisted according to the following agreed [persistence rules](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows#persist-charge)

- [x] (1b) Given a valid charge price list update request is received
when storing it
then it is persisted according to the following agreed [persistence rules](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows#persist-charge)

--
- [x] (2) Given a valid charge update request is received with the exact same master data or price values as currently stored
When processing it
Then is persisted

--
- [x] (3) Given a charge master data update request is received
When processing it
It is only possible to update the following master data fields:
* VAT classification
* TransparentInvoicing (excl fee)
* Name
* Start
* End
* Description

Hence:
Resolution and TAX indicator cannot be updated. 

--

- [x] (4a) Given a charge (master data) update request is received
When the intention is to update **master data**
Then the correct business reason code for updating master data must be used

--

- [x] (4b) Given a charge (price list) update request is received
When the intention is to update **prices**
Then the correct business reason code for updating prices must be used

--

- [x] (4c) Given a charge update request is received and processed
When DataHub sends out notifications
Then it uses the same business reason code as the one provided in the update request.

--

- [x] (4d) Given a charge **master data** update request is received
When processing it
Then all master data fields must be populated in order to be accepted
And should any charge prices be included in the same request, they are ignored and will not be forwarded in outbound notifications.

--

- [x] (4e) Given a charge **prices** update request is received with the mandatory master data fields for identification (Charge ID, Owner, Type and "effectiveDate" as well)
When processing it
Then other fields are ignored
And outbound notifications will also only include mandatory master data fields for charge identification

--

- [x] (5) Given Energinet, as System Operator, updates or stops a tax tariff
When processing this
Then Grid Access Providers must receive notifications about it (immediately - 1 hour SLA)

--

- [x] (5a) Given Energinet, as System Operator, updates prices for a tax tariff
When processing this
Then Grid Access Providers must receive notifications about it (immediately - 1 hour SLA)

--
- [x] (6) Given a charge has been stopped
When submitting an update to the same charge with an effective date
* BEFORE the stop date => accept the update, retain the stop date.
* EQUAL TO the stop date => this is considered a 'cancel stop'
* AFTER the stop date => reject it

~AC 7 Removed, added to charge link feature

- [x] (8) Given a Grid access provider, 
when sending a charge stop of charge master data 
then Grid  access provider is able to cancel this, if within predefined time limits governing the environment (-720 days in U,T, B environments),
and if the stop is passed the time limit, then the request is denied. 

--

--
- [x] 11 Given a bundle charge information message
containing a 'create', an 'update' and a 'stop' (in this order)
When processing this
Then all three operations are persisted showing this chronological order.

--
- [x] 11a Given a bundle charge prices message
containing a 'create', and an 'update' (in this order)
When processing this
Then the operations are persisted showing this chronological order.

--
- [x] 12 Given receival of charge requests
When having stored the updates,
Then we publish integration events

## Related user stories:
Charges - create test scenarioes for create, update and stop charges
https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/energinet-datahub/geh-charges/204

Rules for updating charges
https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/energinet-datahub/geh-charges/288

**Comment by HenrikSommer** [comment]
Maybe "Maintain charges (master data) and charge price lists" and "display charges (master data) and charge price lists via GUI" could/should be split into two features?

The Problem Description mentions "stop charge and charge price lists", but it is mentioned in the "Scope" section that "stop" will result in mass updates of charge links which are considered "out-of-scope". It seems to me that we thereby compromise the data integrity of the system(?)

**Comment by jonasdmoeller** [comment]
Activity diagram illustrating the existing maintain charge flow and the new price flow to be developed in #1409, #1410, #1411 and #1413.
![Maintain charges feature.jpg](https://images.zenhubusercontent.com/60dafff3568c156496e54f35/eae26285-ae5d-48bb-9b49-b178ce547046)

**Comment by PerTHenriksen** [comment]
ACs removed from feature: 


OUT OF SCOPE, to be moved from feature
 9 Given a grid access provider
when sending multiple charges, 
then datahub must process them in the order of receival

--
OUT OF SCOPE:
- [] 10 Given a grid  access provider and a stopped charge
when submitting a charge link
Then the charge link period must be for a period where the charge is active, otherwise it's rejected
