### ISSUE TITLE
Live monitor health state of environments

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#1100]
**Synopsis**
As team Volt feeling responsible for the operations of the charges domain in deployed environments
We want to monitor the health status in the environments
So that we can react fast when an environment health state deteriorates.

**Tech notes**
Should/must we transition to using the health monitoring capabilities of Azure Portal instead of our semi self-made solution? Team Mighty Ducks is investigating the possibilities provided by Azure, and might come up with [a solution to be used by all GreenEnergyHub domains](https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/178)

**Acceptance-Criteria**
- [ ] 1: Extend Dan's work with health points with the remaining dependencies for Charges FunctionHost and Charges WebAPI e.g. database connections, service bus topics and queues. 
- [ ] 2: Alter existing system test to check the new health endpoints
- [ ] 3: ~~(Consider if this make sense due to parallel "DevOps alert" work) Given a health monitoring endpoint
When the health of the charges domain is not ok
Then a notification is received in the Microsoft Teams channel "Volt Technical Reports" within 10 minutes~~

**Task list:**
- [x] Extend function host with remaining topics, subs and queues. [PR1238](https://github.com/Energinet-DataHub/geh-charges/pull/1238)
- [x] ~~Extend Charges Web API - if needed~~ Nothing to extend here.
- [x] Remove old way of health checking, which is now deprecated [PR1241](https://github.com/Energinet-DataHub/geh-charges/pull/1241)
- [x] Remove or port health check tests [PR1241](https://github.com/Energinet-DataHub/geh-charges/pull/1241)
- [x] Update existing system test that checks health [PR1241](https://github.com/Energinet-DataHub/geh-charges/pull/1241)
- [x] Remove postman sample request for old health check endpoint

**Comment by prtandrup** [comment]
**For the tester;** 
<hr>

For AC 1:

Step 1) In Postman, use the request **FunctionHost - HealthCheck (Ready)** found in Samples/System folder against U-001 and verify a 200 OK "Healthy" response.

Step 2) In Azure Portal, find the configuration for functionhost in U-001 and change something in the value for environment variable **DOMAINEVENT_MANAGER_CONNECTION_STRING,** which is needed to check the topics and subscription internally in the Charges domain.

Step 3) Do the same call in Postman and verify a **503 Service Unavailable - Unhealth response**

For AC 2: Was part of this [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1241) Not sure it needs further testing than the review.
