### ISSUE TITLE
BUG: Update default charge owner text on gui (PI8b)

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1123]
**Synopsis**
We need to update the text on GUI on b-002 when creating default tariffs. XYZ is not an actor

![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/286c9d9f-de44-4ce5-a92e-713f28f7c362)

**Tech Notes**
~~An easy - but badly designed - solution was made in PR #1125. It is now being replaced by PR #1129 as the first in a series of PRs, which intend to pull actor data for the frontend via the BFF, which in turn must pull the data from the actor register and _not_ from the charges domain. The charges domain is responsible for serving charge data but not data from other domains.~~ Charge owner text is allowed to be delivered by the Charges domain (Architect has signed off)

Currently, Market Participant name is NOT part of the data model in Charges. This needs to be expanded and filled by consuming integration events (published by the Market Participant domain).

**Acceptance-Criteria**
- [ ] Given a metering point with charge links is looked up in DH frontend, 
When looking at the list of charge links, 
Then text in the UI shows the correct charge owner name (as known by the Charges domain) and the Charge Owner GLN.

**Task list:**

- [ ] Extend Market Participant model with `Name` and ensure that it is persisted upon receiving ActorUpdatedIntegrationEvent from Market Participant domain
- [ ] WebApi must serve a ChargeOwnerName that equals MarketParticipant.Name when ChargeLinksController receives GetAsync requests.
- [ ] Remove the contract `ChargeLinkV2Dto` and related functionality in both Charges and Charges.Libraries 
- [ ] More :)?

**Comment by BjarkeMeier** [comment]
Tasks:
- Complete PR #1129 to clean up the API and client to be used by the BFF
- Add API in actor register to expose a suitable endpoint for requesting actor names for the charge owners needed by the UI
- Add a client NuGet package for the actor API to be used from the BFF
- Update the BFF to serve the charge links with the owning actor names from the actor register

**Comment by prtandrup** [comment]
Name is not part of the existing ActorUpdatedIntegrationEvent. Either it needs to be added there, or this story must be postponed until Charges are using the newer more detailed market participant integration events.

**Comment by prtandrup** [comment]
Now the client package used by the BFF targets the v1 of the chargeLinksDto. So Market Participant GLN (aka. charge owner) is yet again displayed in the frontend including the `<Aktørnavn XYZ>`, which this story is intended to solve.
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/7e8b6e04-002d-4427-b764-b61e3329008e)

**Comment by prtandrup** [comment]
As Titans has free capacity, I've gotten a go-ahead from their PO to create this story on their backlog:

https://github.com/Energinet-DataHub/geh-post-office/issues/792 - Include actor name in `ActorUpdatedIntegrationEvent`

**Comment by prtandrup** [comment]
Closing this story, as Charges will be switching to the latest market participant version (with the micro integration events). Some of those events contain MarketParticipant Name, which this [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1620) has already laid the ground for can be persisted in Charges and then served by Charges Web API.

On another note, ChargeLinksV2Dto will be removed at a appropriate moment.
