### ISSUE TITLE
Find and display charge details on GUI

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1130]
Feature 2. 
As a grid company, and as SYO
We want to be able to verify state of charges and charge price lists
by use of  GUI. 

## Parties: 
please involve Jean Mølris (JEM) and Birgitte Friis-Pedersen (BFP) in subsequent feature refinement of gui framework. 

## Definition of scope
-------------
Link to knowledge base on GUI:
https://miro.com/app/board/o9J_kq0bac0=/
------------

## Acceptance criteria 

- [ ] 1a Given a Grid operator, SYO
when having updated charges, 
then I would like to verify that these changes are carried out 
by *searching for charges in the GUI, with the condition, that only **applicable price owners are displayed (
(*see https://miro.com/app/board/o9J_kq0bac0=/ for graphical interface details)
(**SYO can see all see all price owners, grid operator kan only see those they are authorized to see)

- [ ] 1b Given a GUI user,
when having updated charges, 
then I would like to verify that these changes are carried out 
by inspecting the details in the GUI
(see https://miro.com/app/board/o9J_kq0bac0=/ for graphical interface details)

- [ ] 2 Given a Grid operator, SYO
when having updated charges, 
then I would like to verify that these changes are carried out 
by seing the changed charge name in the search metering point screen, on {updated charge names, and transparent invoicing} on charge links

For

**Comment by PerTHenriksen** [comment]
8/3: design workshop; aftalt at vi jagter søgeskærmbillede som første delmål. René kan trække IRS og PTH ind til sparring. 
IRS finder én fra supporten, som kan give sine behov med.

**Comment by PerTHenriksen** [comment]
dependency til #391
