### ISSUE TITLE
Persist Charge (1/4) - Update flow

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1151]
**Synopsis:**
As a Grid Access Provider,
I want to update my charges with new master data,
So that I may correct mistakes or keep the master data aligned with my own system

This is the first of a few stories with the goal of implementing the [charge persistence rule set](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows#persist-charge) (master data only)

With this story we will implement the **update** flow, highlighted below:
<hr>

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/6b9cdd55-a93d-4693-8b37-c06e6c235f65)

<hr>

**Notes:**
Out of scope: Publishing [ChargePeriodUpdated](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargeperiodupdated) integration event

**Acceptance criteria:**

- [ ] 1 Given a charge exist
When processing a charge update request with effective date `after` the charge was created
Then the persisted result must be like this:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/72cf10a3-b8e8-46bb-b17c-f5ef424071e6) <br>

- [ ] 2 Given a charge exist with 3 master data periods
When processing a charge update request with effective date `inside` existing period (1) 
Then the persisted result must be like this:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/6b3dacd8-f01b-4b9b-8803-b621608bf380) <br>

- [ ] 3 Given a charge exist with 3 master data periods
When processing a charge update request with effective date `equal to` period (2) start date
Then the persisted result must be like this:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/81398847-1ff8-4ea5-910c-15b8aa37cb4c) <br>

- [ ] 4 Given a charge exist
When processing a charge update request with effective date `before` the charge was created
Then the persisted result must be like this:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/ff65b35a-b242-465b-9630-f7170e610df4)

- [ ] 5 AC1-4 is done as System Operator with a tax tariff, verify that all grid access providers receive a notification containing the update (Only effectiveDate, no terminationDate in CIM XML)

<hr>

**Task list:**

- [x] Split Charges table into Charges and ChargePeriods (consider what master data fields are dynamic and what are static) - by [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1163)
- [x] Migration/Clean-up dbup script to ensure data consistency 
- [x] Test first: Add update scenarios as tests ([source](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/process-flows/images/PersistingCharges_Update_And_Stop_MasterData_Examples.png))  - by [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1167)
- [x] Introduce a temporary stop charge requests validation rule - [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1161)
- [x] Remove ChangingTariffVatValueNotAllowedRule + tests - by [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1163)
- [x] Remove ChargeUpdateNotYetSupportedRule - by [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1167)
- [x] Update validations.md with the add/removed validation rules - by [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1167)
- [x] After introducing the ChargePeriod table, ensure that the OData controller still works as expected
- [x] After introducing the ChargePeriod table, ensure that the scaffolding script in the .QueryApi project still works as expected by [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1163)
- [x] Update the postman OData script to be able to get ChargePeriod data
- [x] Update ChargesDataModel documentation in GitHub, [link](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/data-models) - by [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1165)

**Comment by prtandrup** [comment]
Task list related:
#### Data model
**Static:**
SenderProvidedChargeId
Type
OwnerId
Resolution 

**Dynamic:**	
TaxIndicator
TransparentInvoicing
Description
Name
VatClassification
StartDateTime
EndDateTime

**Comment by prtandrup** [comment]
Can be tested with the use of OData.

**Comment by IreneDataHub** [comment]
Tests are made for all types of charge. The tests are performed based on the 5 different acceptance criteria. Everything is found ok
[https://app.zenhub.com/files/345465244/72383506-e1e4-4518-aecd-59f901d611f0/download](https://app.zenhub.com/files/345465244/72383506-e1e4-4518-aecd-59f901d611f0/download)
