### ISSUE TITLE
Ignore prices submitted with a Charge Information (D18) update request (Feature-AC4D and AC2)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1202]
**Acceptance criteria:** 

- [ ] Given a valid charge update request is received with the exact same master data or price values as currently stored
When processing it
Then is persisted and processed as normal

**Task list**

- [x] In `ChargeOperationInputValidationRulesFactory` remove price related rules from `CreateRulesForChargeInformation(ChargeOperationDto chargeOperationDto)`
- [x] If it still applies, remove price related rules from `CreateRulesForChargeInformation()` in `ChargeOperationInputValidationRulesFactory.cs`
- [x] Remove interval and points from `ChargeCimSerializer.cs`
- [x] Update test in `ChargeCimSerializer.cs` which both contains Charge Information and Charge Prices
- [x] Remove points from `AvailableChargeData`
- [ ] Remove `#pragma warning disable CS0618` and `#pragma warning restore CS0618`
- [x] Remove interval and points from `ChargeInformationDto.cs`
- [x] Remove `ChargeDataPoints` table

**Comment by HenrikSommer** [comment]
Testing:

Charge information requests:
- Subscription: OK!
- Tariff: OK!
- Fee: OK!

Charge price requests:
- Subscription prices: OK!
- Tariff prices: OK!
- Fee prices: OK! ("TarId039" as SYO)
