### ISSUE TITLE
Update market participant data through the use of integration events from the Market participant domain

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1208]
As the Charges domain
I want to be able to update the market participant data 
through the use of integration events published by the Market participant domain
So that this becomes an automatic process

**Dependencies:**
- Titans will provide a nuget package
- 1x Titans developer will be available for pair programming for 2 days, helping Volt implementing this and to get feedback.

**Tech notes:**
~~It is assumed that we can continue with our current market participant data in charges and apply integration events on top of that. (this note is obsolete)~~
- Please decide how Volt are to handle fault situations/states

**Acceptance criteria:**
- [x] 1 Charges market participants are automatically updated when integration events are published by the Market participant domain. 
- [x] 2 Remove functionality for manually synchronizing data from Market participant database to Charges database.
- [x] 3 Remove Postman request for synchronizing data
- [x] 4 Throws an exception if market participant with same marketparticipantid is already persisted with another role than the one received in the actor integrationevent
- [ ] ~~5 Throws an exception if the actor integrationevent has multiple roles associated~~

**Task list:**
- [x] Update architecture diagram (charge and charge links) to reflect the Market Participant domain, our new function for consuming the integration events published.

**Comment by x-platformcoder** [comment]
Architecture![CF52F095-8F2D-4527-A2C6-244824DE621A.jpeg](https://images.zenhubusercontent.com/621e27789626c44a088a5ee9/064332cc-bd27-4579-b5a6-580ed4651aa3)![35C8758F-0975-4E92-A31C-7D85F9CEEE1C.jpeg](https://images.zenhubusercontent.com/621e27789626c44a088a5ee9/4834c7ef-f48f-4b40-ae57-6004eaab52c6)

**Comment by x-platformcoder** [comment]
Test af Integration: https://app-webapi-markpart-u-001.azurewebsites.net/swagger/index.html
Der er ikke udstillet noget til GridArea endnu, de har ikke noget der pt. kan oprette disse, det bliver leveret sammen med GridLinks iflg. Jesper fra Titans.

**Comment by prtandrup** [comment]
**Blocked**.
**Reason**: The ActorUpdatedIntegrationEvent includes an .ActorId, which is used as MarketParticipant.Id (and primary key) in Charges. Should the integration event hold several market roles - which is may - then we won't process the event correctly, as the second role to be processed will hit an System.InvalidOperationException: "The instance of entity type 'MarketParticipant' cannot be tracked because another instance with the same key value f..."

**Comment by x-platformcoder** [comment]
**Change:**
The team has decided to keep the current datamodel, that implies that we can only have 1 instance of an actor in our marketparticipant table, so a controlled exception is thrown, if trying to add more than 1 marketparticipant with the same actor id into the table, it is also decided that if we receive an actor integration event with more than 1 role associated to the actor, we will reject the integrationevent with a controlled exception. To check if any of these exceptions has occured the guard that monitors errors in the charge domain must handle these.
