### ISSUE TITLE
Charge domain model - business validations

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#1361]
As a Volt Developer
I want my charge domain model to enforce invariants (validation rules) when doing state changes like, create, update, stop and cancel stop
So that the applicable invariants can be view directly on the domain model
And the way the Charges domain does business validations resembles how other domains do

**Task list:**
- [ ] Move **a single** business validation to the domain model

**Acceptance criteria:**
- [x] 1 Given business validation rules have been moved to the Charge Domain Class
When sending a charge information request that violates a business validation
Then a rejection message is received with correct error code and text
<br>

- [x] 2 Same given
When sending a valid charge information request
Then a confirmation message is received
<br>

- [x] 3 Given a charge information request is received with 3 operations for the same Charge, where
* operation 1 is valid
* operation 2 violates a business rule
* operation 3 is valid

When DataHub has processed this request
Then 

* operation 1 is persisted and confirmation is created
* operation 2 is not persisted and a rejection is created
* operation 3 is not persisted and rejected due to operation 2.

**Comment by x-platformcoder** [comment]
Test completed without any problems found
