### ISSUE TITLE
New Price Flow #4: Publish integration event (ChargePricesUpdated), DataAvailable messages (confirmation, rejections and notifications) to messagehub

### ISSUE THREAD

**Issue by HenrikSommer** [Energinet-DataHub/geh-charges#1413]
This is the fourth story in our journey of separating the Charge price handling flow into its' own architecture and at the same time reducing the architecture needed to process such a request (when compared to a Charge Information request).

With this story, we want to make sure we publish an integration event D08 at least once when we create or make changes to a charge price through a PriceCommandReceived event and to notify the MessageHub that data is available for confirmations, rejections, and notifications. To achieve that goal we want to introduce an outbox pattern.

![outbox.png](https://images.zenhubusercontent.com/621e27789626c44a088a5ee9/eb69238b-a88a-4210-aa81-e27a55a929ae)

**Acceptance criteria:**

- [ ] 1 Given a valid charge price request (D08) for a tax tariff is received
When processing the PriceCommandReceived event
Then a DataAvailableNotification event for each grid access provider is logged to Outbox
Then a confirmation event to the sender is logged to Outbox
<br/>

- [ ] 2 Given an invalid charge price request (D08) is received
When processing the PriceCommandReceived event
Then a rejection event to the sender is logged to Outbox
<br/>

- [ ] 3 Given a valid charge price request (D08) is received
When processing the PriceCommandReceived event
Then a ChargePriceUpdated event is logged to Outbox
<br/>

- [ ] 4 Given an entry in the Outbox that is of type ChargePriceUpdated
When a background worker is triggered at a given time
Then we publish the ChargePriceUpdated integration event to the Servicebus and mark the Outbox entry "processed"
<br/>

- [ ] 5 Given an entry in the Outbox that is of type AvailableDataNotification
When a background worker is triggered at a given time
Then we publish the AvailableDataNotification to the Messagehub, so it can be peeked and mark the Outbox entry "processed"
<br/>

- [ ] 6 Given several entries in the Outbox 
When a background worker is triggered at a given time
Then we publish all the events grouped by type in the Outbox to the Messagebus in the correct order
<br/>

- [ ] 7 Given a failure in publishing an event from an entry from the Outbox of the type ChargePriceUpdates
When a background worker is triggered at a given time
Then we stop immediately with processing more ChargePriceUpdated events from Outbox and throw an exception to preserve the order of integration events
<br/>

- [ ] 8 Given a failure in marking an outbox item "processed" after publishing the event
When a background worker is triggered at a given time
Then we continue with the processing of publishing the events from Outbox
<br/>

**Tasks:**

- [ ] Add new timed function as background worker
- [ ] Introduce new table "Outbox"
- [ ] Persist events in Outbox table
- [ ] Publish confirms, rejections and notifications to the messagehub that data is available
- [ ] Publish integration events to the domains
- [ ] Update charge price architecture diagram
 

**Tech notes:**

* Services consuming the events written to the outbox should be idempotency so they won't misbehave or get into a false state (At-Least-Once Delivery)
* On updates in the charges domain, we should commit all business objects, confirm, reject and outbox objects (notification- and integrationevents) in the same atomic transaction.
* An entry into an outbox table should contain enough information to create the event at a later point in time.
* A background worker that is a timed azure function that polls for new messages in an interval, we should consider how often we poll the database (eg. every 5 sec.?)
* If marking an event as "processed" fails after publishing the event on the Servicebus, it is ok, it will be resend the next time the background worker is triggered and marked "processed"

**Meteringpoint implementation observations:**

* **OutboxWatcher** - triggered function
* **OutboxMessage** - message class
* **OutboxMessageCategory** - category of the event (integration, notification etc.)
* **OutboxTypeFactory** - returns an OutboxMessage with category and type of the event
* **OutboxManager**  - repository
* **OutboxOrchestrator** - handler
* **OutboxProvider** - encapsulates outbox context, calls add on context.outboxmessages
* **OutboxMessageDispatcher** - publish event

**Comment by x-platformcoder** [comment]
added some insight from meteringpoint domain on how they have implemented the outbox pattern. It looks straight forward without any black magic

**Comment by prtandrup** [comment]
Since the creation of this story, a new price flow design has been suggested, see story #1528.
Version 2 of that design is expected to cover integration event `ChargePricesUpdated` and confirmation and notification messages (for price series), see story #1529. Hence, closing this story.
