### ISSUE TITLE
Outbox V1: Introduce Outbox table and OutboxProcessor (New Price Flow #3)

### ISSUE THREAD

**Issue by jonasdmoeller** [Energinet-DataHub/geh-charges#1528]
This is the very first implementation of the [outbox pattern](http://www.kamilgrzybek.com/design/the-outbox-pattern/) in Charges. It is expected to be followed by additional stories that will mature and harden it.

Main purpose for its' introductory is the ability to guarantee that events are sent if and only if the database transaction commits. In this v1 story, the events being DataAvailableNotification events for rejected price series requests.

Scope: 
* Rejection flow in the new Price Series flow. 

![outbox-v1.jpg](https://images.zenhubusercontent.com/60dafff3568c156496e54f35/bf64f28d-a4b4-46b4-8eff-baab29478a99)

[Link til Miro board](https://miro.com/app/board/uXjVO74hWqo=/)

**Acceptance criteria**

- [x] 1 Given a **invalid** charge price request (D08) is submitted
When processing it
Then the sender is able to peek a one - and only one - **rejection** message

**Tasks:** 

- [x] Create new Outbox table 
- [x] New Price Flow persist rejection event in the outbox table
- [x] A timer-trigger function "Outbox processor" reads the rejection event, then it creates and persists AvailableChargeReceiptData
- [x] The same function then notify MessageHub about the rejection message (as a DataAvailableNotification)
- [x] Integration Test created that persists rejected price event data to AvailableChargeReceiptData table (Repository test)
- [x] (Preferred, but not mandatory for story completion) Integration Test created that verifies the Outbox processor retries after a failed attempt to process a rejection event from the outbox table
- [x] The Old Price flow has stopped creating AvailableData for Charge Price Rejections. It still creates AvailableData for Charge Information rejections. So, ChargeRejectionDataAvailableNotifierEndpoint ignores D08 events.

**Testscenarioes:**
- [x] Failing documentvalidation in chargesprices (D08) flow 
- [x] Failing inputvalidation in chargesprices (D08) flow
- [x] Failing businessvalidation in chargeprices (D08) flow (for now, no rejections message will appear)
- [x] Failing documentvalidation in chargeinformation (D18) flow 
- [x] Failing inputvalidation in chargeinformation (D18) flow
- [x] Failing businessvalidation in chargeinformation (D18) flow 
- [x] Test a bundle of mixed invalid/valid chargeprices (D08) flow starting with a valid 
- [x] Test a bundle of mixed invalid/valid chargeprices (D08) flow starting with an invalid 
- [x] Test a confirmation message for chargeprices (D08) flow
- [x] Test a confirmation message for chargeinformation (D18) flow

**Comment by jonasdmoeller** [comment]
[Uploading... outbox-v1.jpg]

**Comment by prtandrup** [comment]
The problem encountered with Volt's test actor in U-001 has been transformed into a bug on Titans' board. See this [issue](https://github.com/Energinet-DataHub/geh-post-office/issues/741)
