### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by HenrikSommer** [Energinet-DataHub/geh-charges#1548]
Continuing a secure and performant it-system requires frequent updates of software components in use by the it-system.

**Acceptance criteria**

- [x] 1 Given the Charges domain
When our software dependencies release new versions
Then we update our dependencies both from within Energinet and 3rd party to the latest stable version

**Tasks:** 
- [x] Update remaining dependencies identified by dependabot on August 1, 2022
- [x] Update Energinet dependencies

**Tech notes:**
- Microsoft.ApplicationInsights.WorkerService 2.21.0 obsoletes the use of _InstrumentationKey_
- Energinet.DataHub.Core.App.FunctionApp 4.1.0 changes the use of _CorrelationContext_
- There is an incompatibility between Energinet.DataHub.Core.Messaging 2.1.0 and Energinet.DataHub.Core.SchemaValidation 2.1.0 so we use Energinet.DataHub.Core.SchemaValidation 1.0.13 for now
- Remember to update _Energinet.DataHub.Charges.Clients_ and _Energinet.DataHub.Charges.Clients.Registration_ as well

**Comment by prtandrup** [comment]
### Regression test done in T-001:
<hr>
**Create Charge:** 
Subscription with ID: SubId022

````
<?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
	<cim:mRID>DocId2022-08-26T06:45:05.506Z</cim:mRID>
	<cim:type>D10</cim:type>
	<cim:process.processType>D18</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-08-26T06:45:05Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId2022-08-26T06:45:05.506Z</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D01</cim:type>
				<cim:mRID>SubId022</cim:mRID>
				<cim:name>Charge name</cim:name>
				<cim:description>The charge description</cim:description>
				<cim:priceTimeFrame_Period.resolution>P1M</cim:priceTimeFrame_Period.resolution>
				<cim:effectiveDate>2022-10-31T23:00:00Z</cim:effectiveDate>
				<!--cim:terminationDate>2023-01-31T23:00:00Z</cim:terminationDate-->
				<cim:VATPayer>D01</cim:VATPayer>
				<cim:transparentInvoicing>false</cim:transparentInvoicing>
				<cim:taxIndicator>false</cim:taxIndicator>
			</cim:ChargeType>
		</cim:ChargeGroup>
	</cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>
````

Confirmation received: 

````
<?xml version="1.0" encoding="utf-8"?>
<cim:ConfirmRequestChangeOfPriceList_MarketDocument xmlns:cim="urn:ediel.org:structure:confirmrequestchangeofpricelist:0:1">
    <cim:mRID>4cbb4b8697ca4f759de8c3166972a7de</cim:mRID>
    <cim:type>D11</cim:type>
    <cim:process.processType>D18</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-08-26T06:45:35Z</cim:createdDateTime>
    <cim:reason.code>A01</cim:reason.code>
    <cim:MktActivityRecord>
        <cim:mRID>f5796871443947a99215f37b86ca3194</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-08-26T06:45:05.506Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
    </cim:MktActivityRecord>
</cim:ConfirmRequestChangeOfPriceList_MarketDocument>
````

Database:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/9d8428bc-74fc-4422-b92f-7aee9073f360)
<hr>

**Submit Price series:**
````
<?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
    <cim:mRID>DocId2022-08-26T06:48:37.548Z</cim:mRID>
    <cim:type>D10</cim:type>
    <cim:process.processType>D08</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-08-26T06:48:37Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>OpId2022-08-26T06:48:37.548Z</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D01</cim:type>
                <cim:mRID>SubId022</cim:mRID>
                <cim:effectiveDate>2023-01-31T23:00:00Z</cim:effectiveDate>
                <cim:Series_Period>
                    <cim:resolution>P1M</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>2023-01-31T23:00Z</cim:start>
                        <cim:end>2023-02-28T23:00Z</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>102.302</cim:price.amount>
                    </cim:Point>
                </cim:Series_Period>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>
````
Confirmation received: 
````
<?xml version="1.0" encoding="utf-8"?>
<cim:ConfirmRequestChangeOfPriceList_MarketDocument xmlns:cim="urn:ediel.org:structure:confirmrequestchangeofpricelist:0:1">
    <cim:mRID>49ecea395f6b4b99bab0e1ff65dcae3d</cim:mRID>
    <cim:type>D11</cim:type>
    <cim:process.processType>D08</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-08-26T06:48:45Z</cim:createdDateTime>
    <cim:reason.code>A01</cim:reason.code>
    <cim:MktActivityRecord>
        <cim:mRID>1aa5747cb8654841bfe1a8bb9cdf34b8</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-08-26T06:48:37.548Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
    </cim:MktActivityRecord>
</cim:ConfirmRequestChangeOfPriceList_MarketDocument>
````

Database:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/2ac10682-8a4c-4f7c-b44b-b6740da6fdf3)
<hr>

TODO: 
**Create Metering Point and verify default links:** 
**Verify links displayed on MP in GUI:**

**Comment by prtandrup** [comment]
Decided to put the Blocked label on #1579 instead, as that particular story has more to do with the integration between Metering Point and Charges, than this story does. 

Testing this story continues.
