### ISSUE TITLE
Closed, replaced by other stories. Redesign of servicebus implementation for charges

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1584]
for now, the issue is for braindump and preliminary refinement

**Tasks:**

- [ ] Switch to using local subscriptions (in Charges repo) covering:
* Market Participant domain's ActorUpdatedIntegrationEvent
* Metering Point domain's <type>MeteringPointCreatedEvents 

- [ ] Figure out what to do with the request-reply setup with Metering Point domain (creating default charge links)
- [ ] Get rid off the local ServiceBus, and let internal topics/queues be owned by the Shared ServiceBus
- [ ] Ensure integration tests and domain tests are still working (unsure how - if at all - they're affected by this?)
- [ ] `HealthCheckConfiguration` will require some maintenance due to this.

**Questions/Notes:** 
* (Peter:) Moving towards a single service bus topic; we will become more reliant on the `MessageType` meta data in service bus messages - not sure we have given this so much attention earlier, due to separate topics - [MessageType link](https://github.com/Energinet-DataHub/green-energy-hub/blob/main/docs/architecture-decision-record/ADR-0008%20Integration%20events.md#message-type)
