### ISSUE TITLE
Minor clean up in outgoing notifications (effectiveDate + cim:snapshot_DateAndOrTime.dateTime)

### ISSUE THREAD

**Issue by jonasdmoeller** [Energinet-DataHub/geh-charges#1633]
While working on #1561, a few things was spotted related to the outgoing Charge Price Notification message (D08) which needs to be cleaned up.

**Tasks:**
- [x] Remove `cim:snapshot_DateAndOrTime.dateTime` from outgoing D08 and D18 notifications (including removal of `CimChargeConstants.SnapshotDateTime`. This tag is **not used** by DataHub3, according to the CIM/RSM guide.
- [x] Remove EndDate property from `AvailableChargePriceData.cs` (time interval end is calculated based on start date)

**Notes:** 
For some reason EffectiveDate is mandatory when Charge Information and Charge Prices are ingested, but it is not mandatory in notifications (Notify Price List).
SME decision: `effectiveDate` must be sent out for Charge Price Notifications although not mandatory in the CIM schema for NotifyChangeOfPriceList (this goes for D18 as well).

**Acceptance criteria:**

- [x] 1 Given System Operator submits a Charge Price (D08) request for a tax tariff 
When Grid Access Providers peeks the Notification (D08)
Then `effectiveDate` is present and holds the same value as provided by the System Operator
And `cim:snapshot_DateAndOrTime.dateTime` is **not** present.
<br>

- [x] 2 Given System Operator submits a Charge Information (D18) request with a tax tariff 
When Grid Access Providers peeks the Notification (D18)
Then `effectiveDate` is present and holds the same value as provided by the System Operator
And `cim:snapshot_DateAndOrTime.dateTime` is **not** present.

**Comment by prtandrup** [comment]
### Tested in T-001 :heavy_check_mark:

**AC1** 
**System Operator submits Charge Price request (D08) for tax tariff with ID: SyoTar0004:**
Request
````
<?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
    <cim:mRID>DocId2022-09-15T11:59:05.254Z</cim:mRID>
    <cim:type>D10</cim:type>
    <cim:process.processType>D08</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>EZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-09-15T11:59:05Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>OpId2022-09-15T11:59:05.254Z</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>SyoTar0004</cim:mRID>
                <cim:effectiveDate>2022-09-30T22:00:00Z</cim:effectiveDate>
                <cim:Series_Period>
                    <cim:resolution>PT1H</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>2022-09-30T22:00Z</cim:start>
                        <cim:end>2022-10-01T22:00Z</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>1.112</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>2</cim:position>
                        <cim:price.amount>2.002</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>3</cim:position>
                        <cim:price.amount>3.003</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>4</cim:position>
                        <cim:price.amount>4.004</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>5</cim:position>
                        <cim:price.amount>5.005</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>6</cim:position>
                        <cim:price.amount>6.006</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>7</cim:position>
                        <cim:price.amount>7.007</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>8</cim:position>
                        <cim:price.amount>8.008</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>9</cim:position>
                        <cim:price.amount>9.009</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>10</cim:position>
                        <cim:price.amount>10.010</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>11</cim:position>
                        <cim:price.amount>11.011</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>12</cim:position>
                        <cim:price.amount>12.012</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>13</cim:position>
                        <cim:price.amount>13.013</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>14</cim:position>
                        <cim:price.amount>14.014</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>15</cim:position>
                        <cim:price.amount>15.015</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>16</cim:position>
                        <cim:price.amount>16.016</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>17</cim:position>
                        <cim:price.amount>17.017</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>18</cim:position>
                        <cim:price.amount>18.018</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>19</cim:position>
                        <cim:price.amount>19.019</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>20</cim:position>
                        <cim:price.amount>20.020</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>21</cim:position>
                        <cim:price.amount>21.021</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>22</cim:position>
                        <cim:price.amount>22.022</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>23</cim:position>
                        <cim:price.amount>23.023</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>24</cim:position>
                        <cim:price.amount>24.024</cim:price.amount>
                    </cim:Point>
                </cim:Series_Period>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>
````

Grid Access Provider got the following notification, where EffectiveDate is 2022-09-30T22:00:00Z as expected and snapshot is gone:
````
<?xml version="1.0" encoding="utf-8"?>
<cim:NotifyPriceList_MarketDocument xmlns:cim="urn:ediel.org:structure:notifypricelist:0:1">
    <cim:mRID>e7029f29b6974ef7bd99f64b2b32c195</cim:mRID>
    <cim:type>D12</cim:type>
    <cim:process.processType>D08</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-09-15T11:59:54Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>a737ef79b7244faa84620de7688b45e6</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>SyoTar0004</cim:mRID>
                <cim:effectiveDate>2022-09-30T22:00:00Z</cim:effectiveDate>
                <cim:Series_Period>
                    <cim:resolution>PT1H</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>2022-09-30T22:00Z</cim:start>
                        <cim:end>2022-10-01T22:00Z</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>1.112000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>2</cim:position>
                        <cim:price.amount>2.002000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>3</cim:position>
                        <cim:price.amount>3.003000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>4</cim:position>
                        <cim:price.amount>4.004000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>5</cim:position>
                        <cim:price.amount>5.005000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>6</cim:position>
                        <cim:price.amount>6.006000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>7</cim:position>
                        <cim:price.amount>7.007000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>8</cim:position>
                        <cim:price.amount>8.008000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>9</cim:position>
                        <cim:price.amount>9.009000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>10</cim:position>
                        <cim:price.amount>10.010000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>11</cim:position>
                        <cim:price.amount>11.011000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>12</cim:position>
                        <cim:price.amount>12.012000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>13</cim:position>
                        <cim:price.amount>13.013000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>14</cim:position>
                        <cim:price.amount>14.014000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>15</cim:position>
                        <cim:price.amount>15.015000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>16</cim:position>
                        <cim:price.amount>16.016000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>17</cim:position>
                        <cim:price.amount>17.017000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>18</cim:position>
                        <cim:price.amount>18.018000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>19</cim:position>
                        <cim:price.amount>19.019000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>20</cim:position>
                        <cim:price.amount>20.020000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>21</cim:position>
                        <cim:price.amount>21.021000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>22</cim:position>
                        <cim:price.amount>22.022000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>23</cim:position>
                        <cim:price.amount>23.023000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>24</cim:position>
                        <cim:price.amount>24.024000</cim:price.amount>
                    </cim:Point>
                </cim:Series_Period>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:NotifyPriceList_MarketDocument>
````

**AC2**
**System Operator submits Charge Information request (D18) with new tax tariff with ID: SyoTar0005:**
Request
````
<?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
	<cim:mRID>DocId2022-09-15T12:01:47.096Z</cim:mRID>
	<cim:type>D10</cim:type>
	<cim:process.processType>D18</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>EZ</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-09-15T12:01:47Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId2022-09-15T12:01:47.096Z</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D03</cim:type>
				<cim:mRID>SyoTar0005</cim:mRID>
				<cim:name>Charge name</cim:name>
				<cim:description>updated The charge description</cim:description>
				<cim:priceTimeFrame_Period.resolution>PT1H</cim:priceTimeFrame_Period.resolution>
				<cim:effectiveDate>2022-09-30T22:00:00Z</cim:effectiveDate>
				<!--cim:terminationDate>2022-08-10T22:00:00Z</cim:terminationDate-->
				<cim:VATPayer>D01</cim:VATPayer>
				<cim:transparentInvoicing>false</cim:transparentInvoicing>
				<cim:taxIndicator>true</cim:taxIndicator>
			</cim:ChargeType>
		</cim:ChargeGroup>
	</cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>
````

Grid Access Provider notification with EffectiveDate equal to 2022-09-30T22:00:00Z as expected and without snapshot: 
````
<?xml version="1.0" encoding="utf-8"?>
<cim:NotifyPriceList_MarketDocument xmlns:cim="urn:ediel.org:structure:notifypricelist:0:1">
    <cim:mRID>b6f57304bfa9422fa2673fb2d57b6c45</cim:mRID>
    <cim:type>D12</cim:type>
    <cim:process.processType>D18</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-09-15T12:02:33Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>1477af10baab47e88cb9835f068dd83c</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>SyoTar0005</cim:mRID>
                <cim:name>Charge name</cim:name>
                <cim:description>updated The charge description</cim:description>
                <cim:priceTimeFrame_Period.resolution>PT1H</cim:priceTimeFrame_Period.resolution>
                <cim:effectiveDate>2022-09-30T22:00:00Z</cim:effectiveDate>
                <cim:VATPayer>D01</cim:VATPayer>
                <cim:transparentInvoicing>false</cim:transparentInvoicing>
                <cim:taxIndicator>true</cim:taxIndicator>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:NotifyPriceList_MarketDocument>
````
