### ISSUE TITLE
GUI - Add price tab to GUI

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1641]
We want to be able to choose "Price" in the sidemenu in the GUI. This should navigate to a page which is empty.

Add price tab to side menu shown in picture.
![image.png](https://images.zenhubusercontent.com/62e91b5d80cfb19b5219a97a/5e3c38b9-a37a-425a-abd2-8c6025e28000)

**Tasks**
- [x] Add feature flag.
- [x] Add "Price" tab in side menu which navigates to an empty page.

**Tech Notes:**

Add feature flag so there won't be pushed an empty page to main.
Ensure that the page can be translated (danish/english).

**Acceptance criteria**

- [x] 1 - As a GUI user, I want to see a new "Price" tab in side menu, which navigates to an empty page.

**Comment by x-platformcoder** [comment]
Testet on T001 and the price tab is visible:
[T001](https://lively-river-0f22ad403.azurestaticapps.net/metering-point/search#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJleHAiOjE2NjM3NjU2MTIsIm5iZiI6MTY2Mzc2MjAxMiwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly90ZXN0MDAxZGF0YWh1YmIyYy5iMmNsb2dpbi5jb20vYjA2OTA5ODEtY2E1Ny00MzYxLWEzOWItMDk4YTVkYTkzNTM0L3YyLjAvIiwic3ViIjoiYTgzZDY0YjEtMGUxNC00ODgzLTkyZGQtNjU3YWZkNGRkOGIxIiwiYXVkIjoiODljMmU5ZmItYzY2NC00MzM2LTgzYWEtNzYwYjg3NTMzMzVhIiwibm9uY2UiOiJkZWZhdWx0Tm9uY2UiLCJpYXQiOjE2NjM3NjIwMTIsImF1dGhfdGltZSI6MTY2Mzc2MjAxMiwidGZwIjoiQjJDXzFfdDAwMV9zaWduaW4ifQ.DG3ZJHqHPOuqmd3kjFRa8qsyQz6aOuiWTNUjnCi8XJo-eA_11nbSiYdKnWk7_9h9S5L5-oiXjN_Ly0NKh0YyX1kIGla752nCrcPIGb2Gslyy55MF5FX5zTv01tvpERpMf_o-xJy9bt308W0i409MMMzJNCUBWfdCOVWBbakW2boZJmd6OhcIgC7_g-JEexdbD1OnKAsgb9eMy8xnRm01NspJaoVlzyMmphXdbt3ydi4q4vs-Gn1Q2E-337Cu_Pz9Wxoe2LxfO0hQXnvnq5D9Kl3omKOpxejYs2wFa99f9eJwjtU_JOAkqzmlrXKIyOWg1WGvz-ugJgY8hXZyN5d75w)

**Comment by x-platformcoder** [comment]
Testet on B002 and the price tab is invisible:
[B002](https://purple-forest-07e41fb03.azurestaticapps.net/metering-point/search#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJleHAiOjE2NjM3NjU3MjgsIm5iZiI6MTY2Mzc2MjEyOCwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9wcmVwcm9kMDAyZGF0YWh1YmIyYy5iMmNsb2dpbi5jb20vNWEzOTZjMzYtZDU2ZS00ZGI0LTg4MGItYzc4OTRmMmQ5OTY2L3YyLjAvIiwic3ViIjoiODJmN2M4NGMtNDAwOC00NTI0LTk5ZjktZDc2ZDJhOWQyODY0IiwiYXVkIjoiMGQ2NjMwMDgtM2NhZS00YjdjLWIxYjAtN2Q2OTkxYjdlY2EzIiwibm9uY2UiOiJkZWZhdWx0Tm9uY2UiLCJpYXQiOjE2NjM3NjIxMjgsImF1dGhfdGltZSI6MTY2Mzc2MjEyOCwidGZwIjoiQjJDXzFfYjAwMl9zaWduaW4ifQ.fCLMzWoFVEYKrbXV-pvzoWEwnobJTtzPtxOg4v-VfSR97uDhKP94IhA4Rt7CsmILAo5lJwbrb8ufAsFyGyh5sKHii8KdABXxnZKJLH56aqzR-GqCL3DI6EOPfDNk4o4Gwmr3y15e8_DBST7UmK8ss_gJy4bPRzdZJYgndkbjAFI47Lij-nStIPl6aBnCBUnhjtiNGuUE0vLzDjvw9qWYE2FbcIE1lxnXBpgTUGodMr-74EL-G0apQbx99jG1ZYCeHiPGm0Jbde1dQOt_oyO5oJLAUwkbuRh_KMqlnB49nvRbMFs3a9k6ntzbJvLxf7dQc0uUmYhccYjJfIfgjq1DYw)
![gui-B002-prices-tab.png](https://images.zenhubusercontent.com/621e27789626c44a088a5ee9/cf225ae0-3868-4d81-9dc7-549c62a3149d)
