### ISSUE TITLE
GUI - Price search page without functionality

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1655]
We want to show which parameters that we can search for price information. 

How the price page should look like in the GUI.
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/dbeef23e-75ad-4ef2-acfb-29b04a8cabfc)

Link to figma for the page and some functionalities:
https://www.figma.com/proto/4tVkjKm5fkIj61nx4XD3pA/DataHub-3.0?node-id=2520%3A24104&scaling=contain&page-id=2419%3A16889&starting-point-node-id=2518%3A42862

**Tasks**
- [x] Create input fields and drop downs menues.
- [x] Create table section
- [x] Add icons in table

**Acceptance criteria**
- [ ] 1 - We can see all the input fields for search parameters shown in Figma.
- [ ] 2 - In the table content there should be no data, but instead show a message like in the picture below
![image.png](https://images.zenhubusercontent.com/62e91b5d80cfb19b5219a97a/7b8bad62-c545-4d4d-a5e2-82336f80c13d)

**Out of scope**
The known price information will not be shown, this is only a visual issue.
ID/Name should not be a dropdown, but just an input field.

**Comment by IreneDataHub** [comment]
Test 27. September 2022
Test environment T-001 ( Feature flag b-001)

Acceptcritirium:
It is possible to see all the input fields for search parameters shown in Figma, but there are the following conditions that differ, but are as desired:
- The column for the icon for forward billing and tax is empty, but the icon are going to be show  when there are conditions that can be searched for = OK
- The columns are correct build up although there is a very wide distance. However, it looks nice when there are prices that can be searched
-unknown disappears when there are conditions that can be filled
-It has been agreed that "prices per page" should be written instead of results per page
- sorting is indicated with a mark when there is data that can be uploaded
- It has been agreed that the calendar function is specified in Danish date format, regardless of whether English is selected as display


In addition, it is desired that the following conditions be corrected:
- ID/Name should not be a dropdown, but just an input field - please remove the arrow
- Definition of the "Validity:
   Valid now "current prices on search day"
   Planned "Prices in the Future"
   This week "prices valid this week"
- Change "ID " to "Price ID" in column and seach

 2 - In the table content there should be no data, but instead show a message like in the picture below

Test OK 
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/18dd63d3-e620-454b-b3cc-5da7a1831bec)
