### ISSUE TITLE
GUI - Show price information in GUI

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1656]
We would like to see all price information in the GUI depending on the parameters.
We would like to be able to sort by all columns in the table.

The GUI user have to search for changed price informations, as the GUI will not automatically update the price information.

PO will qualify the expected number of charges, based on DH2, to support a decision on whether to fetch charges async or syncronious. 

**Tasks**

- [x] Get data from charges domain. 
Data Notes: 
* Use Charge Name from the current charge period
* Use the earliest charge period's start date as Valid from
* Use the latest charge period's end date as Valid To (do not display anthing if the value is = Charges.EndDefault value aka year 9999)

- [x] Get owners to search by.
- [x] Be able to sort on all columns.
- [x] Clear parameters button. Should also clear the result.
- [x] Be able to search by all parameters, excluding other periods than "Gyldig nu" and user defined From and To (disable the inputs).

**Acceptance criteria**

- [ ] 1 - As a GUI user, I can find price informations when searching by using ID/Name.
- [ ] 2 - As a GUI user, I can find price informations when searching by using owner.
- [ ] 3 - As a GUI user, I want to see a updated/new price information in GUI.
- [ ] 4 - The page should look like the figma example and functionality should be working as well.
- [ ] 5 - Switch the feature flags, to turn on the solution in all environments. 

**Out of scope**
Searching using other periods than "gyldig nu" aka (actual) as well as From and To dates.
User/role mgmt not supported, everyone can see all price information
Cannot download loaded price informations.
It is not possible to click on row to see the details about the price information and price series.

**Comment by IreneDataHub** [comment]
Test 14. October 2022
Environment t-001
Status
1 = OK
2 = missing function select all
3 = OK
4 - missing functionalitet

 1 - As a GUI user, I can find price informations when searching by using ID/Name.
Ok - seach result shows when using som letters or figure
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/2933f0cf-472d-4d80-b05e-6b47f39ff555)
 2 - As a GUI user, I can find price informations when searching by using owner.

K, but I want it possible to be able to select all without having to clear first
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/06d2d297-ee33-4dac-b063-74cc96707062)
 3 - As a GUI user, I want to see a updated/new price information in GUI.
OK i have test it in t - 001
Before change
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/5dd00a10-418e-43e4-9e8e-1fdbe0851d35)
After change moms from no to yes
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/efbc9ad1-1f10-4e70-a2d2-13ec5404eaa4)
 
4 - The page should look like the figma example and functionality should be working as well.
OK - but there are som issue in functionalitet. Eg. sort in name, down and up ( perhaps small letters?) Translate to english in resolution. Like to use putun enter in sted of seach. Seach buttun dosenøt work before push twice. And alsåo great to always mark which prise element we are click into
 5 - Switch the feature flags, to turn on the solution in all environments.

**Comment by IreneDataHub** [comment]
18. October 
Test t-001 and B-002
Acc. 2
It is possible to sorting using owner. Mighty Ducks has a storie for a parameters for "select all". Therefore = OK

Acc. 4 = OK
Sort in name works, down and up, but there are also a function without anykind of sort,
Translate = OK
Seachbuttun - fix later
