### ISSUE TITLE
GUI - Add drawer with breadcrumbs to price search page

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/geh-charges#1684]
When clicking on a charge item in the search result, we would like to open a drawer. This drawer should be empty for now, except for the breadcrumbs on top.

![breadcrumbs.png](https://images.zenhubusercontent.com/626fbc6d95e6587091961d95/62bd7beb-cd65-4044-924b-4a6338202c13)

**Tasks**
- [x] Open a drawer when clicking on a table row
- [x] Create a breadcrumbs component and show in drawer top bar

**Acceptance Criteria**
- [ ] As a GUI user, I want to open a drawer when clicking on a table row
- [ ] As a GUI user, I want to be able to see the current path in the drawer (breadcrumbs)

**Clarifications**
- Is the "Priser" text in the breadcrumbs clickable?
- Should the drawer state be part of the URL? (might be needed for #1690)

**Comment by IreneDataHub** [comment]
Test t environment 10.10.22
Acc criteria:
 As a GUI user, I want to open a drawer when clicking on a table row = OK
 As a GUI user, I want to be able to see the current path in the drawer (breadcrumbs) = OK

It is possible to open a page regardless of where you click on the search result ( price id, name, Owner etc)
It is possible to swich between pris ID and price search page, when you click at the next price id.

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/4ebb14cb-d90d-459f-a241-ebb1ce729268)
