### ISSUE TITLE
GUI - Add header to price details drawer

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/geh-charges#1685]
We would like to display some details for the selected charge price.

![header.png](https://images.zenhubusercontent.com/626fbc6d95e6587091961d95/e8479b06-1d36-49cd-8671-c5838f600593
)

**Tasks**
- [x] Use watt-drawer-actions to add some buttons (should be disabled for now)
- [x] Display header with type, name, owner and id? next to actions
- [x] Create expandable description area (what should go here?)
- [x] Add "table" view for the remaining metadata
- [x] Get price, description and vat from the WebApi.

**Acceptance Criteria**
- [ ] As a GUI user, I would like to be able to see detailed information in the drawer
- [ ] As a GUI user, I would like to be able to expand a panel for a detailed description

**Comment by PerTHenriksen** [comment]
Greyed out text is out of scope i.e. "pris opdateret, stamdata opdateret"

**Comment by HenrikSommer** [comment]
We have agreed with @IreneDataHub that it is more valuable to show the validity dates (from and to) instead of the "Pris" and "Gyldighed" showed in the screenshot from Figma.

**Comment by IreneDataHub** [comment]
Test 14. October 2022
Environment T-001

Danish language = OK
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/4cf024f8-b835-44a2-9a71-ee9d3a736367)
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/3c5e29b5-df3e-4490-8b01-441398fb187f)

English translate missing for tax, transparent invoiving
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/c04095ca-b171-45a1-8a96-18831c92b690)
