### ISSUE TITLE
GUI - Add daterange picker within drawer tabs

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/geh-charges#1687]
We would like to be able to show a daterange picker in the tabs view.

![datepicker.png](https://images.zenhubusercontent.com/626fbc6d95e6587091961d95/2c2343d3-e159-41fc-a610-fda31f156a07)

**Notes**
Step functionality as well as the chips (Dag, Uge, Måned, Kvartal, År) should be out of scope for now, since the component is currently on track to be implemented in Watt.

**Tasks**
- [x] Add daterange picker to tabs view (should not be connected to table data yet)
- [x] Feature flag chips.

**Clarifications**
- Should the date selection carry over between tabs? Or should they be considered entirely separate?
- Should the daterange picker have a default? Is it possible to search for all items (no date range)?

**Acceptance Criteria**
- [ ] As a GUI user, I want to be able to filter my results based on a date range.

**Out of scope**
The chips is not a part of this story because the frontend team is making the functionality.

**Comment by x-platformcoder** [comment]
udeståender:
mangler at få changes fra datepickeren over på de andre faner
datepickeren viser ikke initial value korrekt, Bjørn kigger på problemet,
der er angivet nogle todo's på tests jeg mener der skal laves inde i dh-drawer-datepicker.component.spec.ts

**Comment by IreneDataHub** [comment]
21. October 
T-001
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/05db5d80-a940-48a2-bb8c-b7cd5651fe5c)

Tab is showing as expected. Calenderfunctionn works. Out of scope ( another storie) functionality is first comming later,
