### ISSUE TITLE
GUI - Add table view to prices tab in drawer

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/geh-charges#1688]
We would like to display a table view of the individual prices.

![prices-table.png](https://images.zenhubusercontent.com/626fbc6d95e6587091961d95/eb7ba75c-5bf0-437e-afc8-0892e61aa602
)

**Technical Notes**
Consider creating a shared component for the table view, since it is used in all three tabs plus the search page.

**Tasks**
- [x] Fetch data automatically (or just take from response, see below)
- [x] Display table with data
- [x] Hook up table data with date range picker
- [x] Sort on all columns (in the backend)
- [x] Pagination in backend
- [x] Always show 6 decimals in price
- [x] Show different notification if price information has no price series at all. Also disable the datepicker.

**Clarifications**
Should the data be loaded asynchronously when the drawer is opened or is it included in the initial search result?

**Acceptance Criteria**
- [x] As a GUI user, I want to be able to view individual prices related to a charge.

**Comment by PerTHenriksen** [comment]
From standup today, please consider screen real estate; consider having more lines presented, there seems to be a lot of wasted space.

**Comment by HenrikSommer** [comment]
Test: I created a new tariff through our B2B process, found the tariff in the Prices search function and found a nice screen telling me that no prices exist on the tariff:
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/16785e7a-4a7b-4c9b-8bc0-be822c8d303a)
That was fine. I then created prices on the tariff and assured that they were in fact created in the db, but I was not able to view the new prices in the Prices tab. Still the same screen telling "No prices". The only way to force the view to show the prices was through a page refresh and a new search for the price. I suggest we improve this functionality.

Apart from the inconvenience described, the AC is covered.
