### ISSUE TITLE
GUI - Add header to message details page

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/geh-charges#1691]
We would like to display some information regarding the currently selected message.

![message-header.png](https://images.zenhubusercontent.com/626fbc6d95e6587091961d95/2f67371a-70df-40bb-b6da-48e3a0670784
)

**Tasks**
- [ ] Fetch message data based on URL 
- [ ] Create a header view with basic information

**Technical Notes**
Some elements of the header resembles that of the drawer header, perhaps it can be reused.

**Acceptance Criteria**
- [ ] As a GUI user, I want to see some details of the message I have selected.
