### ISSUE TITLE
GUI - Add XML view to message details page

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/geh-charges#1693]
We would like to display the raw XML in a code view.

![message-xml.png](https://images.zenhubusercontent.com/626fbc6d95e6587091961d95/0e2a0886-57be-4f39-af3f-23019c706b61
)

![message-page.png](https://images.zenhubusercontent.com/626fbc6d95e6587091961d95/19e6d6f7-61d1-4be4-beed-82959c87af3a
)

**Notes**
The line numbering should be out of scope for now. Use a textarea field instead.
**Tasks**
- [x] Include sender in fetch response
- [x] Display sender above textarea
- [x] Include XML data in fetch response
- [x] Display XML in textarea
- [x] Display header info above textarea
- [x] Remove download button from list. Not needed to download the list of messages.  
- [x] Open content in drawer, w. breadcrumb. Download button on line. With nice graphics.  

**Clarifications**
Is download button also out of scope?

**Acceptance Criteria**
- [ ] As a GUI user, I want to be able to see more technical details regarding a message.

**Comment by IreneDataHub** [comment]
test 8.11
Environment T -001 
Some issue as has to be fix before thise ticket works as expect (acceptcriteriums)
1:
When using download function (XML file) from the draweren - the draweren close down - It is not expect to close down
2:
Sometime there isn't any XML file - it look likes it is not everytime push at the link find the message
3:
There is an incorrect indication of the message id in the XML file. It fetches, for example, for the 3.11. even though the message was sent on 28.10. eg. DocId2022-10-28T08:23:47.993Z -> DocId2022-11-03T15:02:27.230.
OBS remember UTC time and wristwatch time

I have explaine the issue for Morten så he know that I mean:-)

**Comment by ShaBloze** [comment]
When clicking the download button, the drawer closes. The drawer should stay open.

**Comment by IreneDataHub** [comment]
TGest 14.11.

**Comment by IreneDataHub** [comment]
Test 14.11
Environment T-001

1: now OK
When using download function (XML file) from the draweren - the draweren close down - It is not expect to close down
2: = OK but first for the mesage send in from medio November
Sometime there isn't any XML file - it look likes it is not everytime push at the link find the message
3: OK but first for the mesage send in from medio November
There is an incorrect indication of the message id in the XML file. It fetches, for example, for the 3.11. even though the message was sent on 28.10. eg. DocId2022-10-28T08:23:47.993Z -> DocId2022-11-03T15:02:27.230.
OBS remember UTC time and wristwatch time
