### ISSUE TITLE
GUI - Add test for the charge details view (drawer)

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/geh-charges#1696]
We need to add tests for all the functionality in the drawer.

**Tasks**
- [x] Set up mocking for use in tests
- [x] Add tests for as much as possible :)

**Acceptance Criteria**
- [x] As a developer, I want to be confident that my code will not break in the future.

**Comment by HenrikSommer** [comment]
Test: OK!
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/4e2236ca-d4f2-485a-92ae-e21f8d2bdfaf)
