### ISSUE TITLE
Make SLIs great again: fix the operation_Id issue

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1770]
With this story we intend to 
(1) Fix so that a request can be traced through Application Insights all the way to MessageHub getting notified.
(2) Make the existing Charges' SLI workbook* work again

* Log on to Azure -> Find the Charges Resource group -> Open the Volt SLI -> Open work book

This story is related to the 'broken SLI investigation' in #1734.

**Acceptance criteria:**

- [x]  1 Given a valid Charge Information Request (D18) is submitted
When a Volt Developer uses the http response's correlationId when searching in Application Insights
Then the trace results shows the processing of it; from ChargeIngestion to MessageHub is notified.
<br>

- [x] 2 Same thing, but for Charge Prices Request (D08)
<br>

- [x] 3 Given Charges' SLI workbook is opened
When inspecting the single SLI that exists
Then it shows data and **isn't** flatlined, like seen below:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/756399ce-366a-4179-a11c-c1c0f32d363c)

**Task List:**

- [ ] Make structured logging work in isolated functions, so we can get Correlation Id as a custom dimension in Azure logging.
- [ ] Make workbook work again with new logs using correlation id.

**Comment by prtandrup** [comment]
### Tested in T-001 :heavy_check_mark:

**AC1** 
``` 
Given a valid Charge Information Request (D18) is submitted
When a Volt Developer uses the http response's correlationId when searching in Application Insights
Then the trace results shows the processing of it; from ChargeIngestion to MessageHub is notified. 
```

Submitted D18 request with TarId062 and got **correlation id** back: `573a7d5f-72f3-4efa-8de7-203229976c71`

When using the correlation id in App insights, it is possible to see the processing all the way:

**From Ingestion:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/cae0560c-5e49-4ad2-8d4b-c73469cd83ac)

**From Outbox and towards MessageHub:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/3450edbc-9f6c-472b-95b7-5a824ed99550)

<hr>

**AC2** 
```
Same thing, but for Charge Prices Request (D08)
```

Submitted D08 request and got back correlation id: `942305e5-4fca-40f5-91ad-31d1547f42f9`

App insights...

**From Ingestion:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/f6a0e34c-5d1c-4d3a-9dce-d3cee751d717)

**From Outbox towards MessageHub:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/59c7bada-0534-4264-be67-532fe3bdf5ad)

Logging deviates a bit from Charge Information. This should be investigate at a later point, why this is.

<hr>

**AC3**
```
 Given Charges' SLI workbook is opened
When inspecting the single SLI that exists
Then it shows data and isn't flatlined, like seen below:
```

I've submitted two D18 requests today, and they appear in the SLI:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/75afdf1d-6be1-42c3-92d9-1e6cc4f38cf8)
