### ISSUE TITLE
Create  and maintan charges, information and prices, via GUI

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1774]
## Problem
In addition to creating and maintain charge information and charge prices via b2b, we would like to enable GUI users to do the same. 

## Accept Criterias
- [ ] AC 1: Create and maintain charges information via GUI

- [ ] AC 2: Maintain charges information via GUI

- [ ] AC 3: Create and maintain charges prices via GUI

- [ ] AC 4: Maintain charges prices  via GUI
