### ISSUE TITLE
Persist Charge Information History and enable the Web API to query the data

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1846]
Based on the persistence technology selected in #1841, this story is about implementing the historical data model for charge information and being able to populate it with data from accepted Charge Information events, so it can be queried through Charges Web API.

Decision from #1841: Built a custom solution based on service bus, a history function and custom history table(s).

This is considered our query stack.

**Acceptance criteria:**

- [x] 1 Documentation created/updated in GitHub:
* **Charge Information History data model** to be documented [here](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/data-models).
* ~~**Charge Information History persistence flow** to be documented, similar to [this](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows#persist-charge-information).~~
* **Architecture diagram** updated

- [x] 2 Given a "charge history" Web API request
When inspecting the response 
The response must as a minimum include the following data:

* Period start
* Period end
* Name
* Description
* Resolution
* Transparent invoicing
* VAT classification
* Tax
* Type
* Owner
* (Additional data might be needed for coupling it with the charge)

- [x] 3 Given a charge has been created with the following periods (simplified to name updates only)

* 01/01/2022 08:02 AM: ChargeA is created with Name: "Name A0" with effective date: 01/02/2022
* 01/01/2022 08:15 AM: ChargeA is updated with Name: "Name A1" with effective date: 01/02/2022
* 03/01/2022 10:00 PM: ChargeA is updated with Name: "Name B" with effective date: 01/04/2022
* 04/01/2022 09:00 PM: ChargeA is updated with Name: "Name A2" with effective date: 01/02/2022
* 05/01/2022 05:01 AM: ChargeA is updated with Name: "Name future" with effective date: 01/01/2024

When below requests are made, 
Then the following response are returned

[**a**] Request with datetime input: 01/01/2022 08:14 AM 
the response contains 
ChargeA with "Name A0" per 01/02/2022

[**b**] Request with datetime input: 01/01/2022 08:16 AM 
the response contains 
ChargeA with "Name A1" per 01/02/2022

[**c**] Request with datetime input: 03/01/2022 10:01 PM:
the response contains 
ChargeA with "Name A1" per 01/02/2022
ChargeA with "Name B" per 01/04/2022 

[**d**] Request with datetime input: 04/01/2022 09:01 PM:
the response contains 
ChargeA with "Name A2" per 01/02/2022
ChargeA with "Name B" per 01/04/2022 

[**e**] Request with datetime input: 05/01/2022 09:01 PM:
the response contains 
ChargeA with "Name A2" per 01/02/2022
ChargeA with "Name B" per 01/04/2022 
ChargeA with "Name future" per 01/01/2024 

**Task list:**

- [x] Define Charge History Data Model (Peter)
- [x] Create table (Peter)
- [x] Create Azure Function for persisting charge history data based on Charge Information Accepted Event (Jan)
- [x] Create endpoint in Charges Web API that serves the history data (Peter)
- [x] Update architecture diagram (Peter)
- [x] Change schema name so it does not contain Query (Jan)

**Comment by prtandrup** [comment]
I've added a blocked label to this, although some of the work can commence. It is just to make aware that database migrations are currently not done in CD, due to the switch to DbUp.Reboot. Reach out to MD (Kristian) to get the latest on this.

**Comment by prtandrup** [comment]
Blocked label removed. Migrations are now available again in CD.

**Comment by prtandrup** [comment]
**For the tester:**
For AC 1:
-  ChargeHistoryDataModel.png can be found [here](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/data-models/Query).
- Architecture diagram can be found [here](https://github.com/Energinet-DataHub/geh-charges/blob/main/ARCHITECTURE-ChargeInformation.png).

For AC2; use Postman: Samples collection \ Charges Web API \ ChargeHistory \ SearchAsync - will require a token from the frontend. The request body is ready for use.

For AC3: Not possible to test manually; instead see this automatic test: `SearchAsync_WhenCalled_ReturnsChargeHistoryBasedOnSearchCriteria` in `ChargeHistoryQueryServiceTests.cs` which covers this AC.

**Comment by prtandrup** [comment]
Tested in U-001 (OK with team due to CD issue) :heavy_check_mark:

AC1 - see prev comment

AC3 (and implicitly AC2):

**ChargeA** created with the following history:
Charge ID in db: 9AC9E7EE-26C1-48CC-B8B1-484048678056

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/b888737a-5d7f-4549-b01e-e15ed6886f79)

**[a]** Request with date just before Name A1 was registered: (2022-12-20 07:31:13.8339383)

Request & Reply:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/3c306dec-4b0c-4451-b4ba-a4d13ba1a30c)

**[b]** Request with date just after Name A1 was registered: (2022-12-20 07:31:13.8339383)

Request & Reply:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/0529eac1-8ad9-4a90-a7d1-ef394dd9d969)

**[c]** Request with date just after Name B was registered: (2022-12-20 07:31:49.8777157)

Request & Reply:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/05643783-cbbc-422f-9984-54072a920e1a)

**[d]** Request with date just after Name A2 was registered: (2022-12-20 07:32:13.0813230)

Request & Reply:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/27a12c63-3c3d-4ca5-8242-a09633a071d1)

**[e]** Request with date just after Name A2 was registered: (2022-12-20 07:32:46.5681449)

Request & Reply:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/f883f794-49bb-4850-bb21-8547359f52e7)
