### ISSUE TITLE
Publish Charges + Charge Prices integration events on ServiceBus (for aggregations) (updates and stops)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#372]
**Synopsis**:
With this story we implement the means to publish all events for charges and charges prices (to fulfill the charge data needs in the Aggregation domain).

**Tech notes:** 
- When `environment = U`: Events are published to a ServiceBus in the Charges Domain
- When `environment = T`: Events are published to a Shared ServiceBus
- Protobuf is used.

**Preconditions:**
- Charges and charge prices events and contracts have been defined and documented by story #352 => see [contracts](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md)
- Story #288 must be implemented, as this is needed to e.g. determine if an operation is an update of a charge.

**Acceptance criteria**
- [ ] AC#1 Charge Events\* are published to ServiceBus adhering to their defined protobuf [contracts](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md):
<br>
- Given a ChargeCommand is received with a brand new charge (ID, type and owner combination unknown), 
When publishing this as an integration event, 
Then a `ChargeCreated` [event](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargecreated) is published.
<br>
- Given an existing charge
And a ChargeCommand is received for the same charge with a lower StartDateTime than the existing one
When publishing this as an integration event, 
Then a `ChargePeriodUpdated` [event](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargeperiodupdated) is published with `ChargePeriod.StartDateTime` equal the ChargeCommand's StartDateTime
<br>
- Given a ChargeCommand containing a stop for an existing Charge is received (Stop is when StartDateTime and EndDateTime of a ChargeCommand are equal)
When publishing this as an integration event, 
Then a `ChargeDiscontinued` [event](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargediscontinued) is published with ChargePeriod.EndDateTime set according to the stop date.
<br>
- Given a charge has been stopped 
And a ChargeCommand is received for the same charge with StartDateTime equal to the stop date (which must revive the charge)
When publishing this as an integration event
Then a `ChargeDiscontinuationCancelled` [event](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargediscontinuationcancelled) is published with CancelledEndDateTime set to the stop date (same as the ChargeCommand's StartDateTime).
<br>

- [ ] AC#2 The Charge Prices Event\* is published to ServiceBus adhering to its' defined protobuf [contract](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargepricesupdated):
<br>
- Given a ChargeCommand is received with a brand new charge (ID, type and owner combination unknown) that includes charge prices
When publishing this as an integration event
Then a `ChargePricesUpdated` event is published with correct `UpdatedPeriod` and all the prices of the ChargeCommand
<br>
- Given a ChargeCommand is received, which updates existing prices for the same Charge
When publishing this as an integration event 
Then a `ChargePricesUpdated` event is published with correct `UpdatedPeriod` and all the prices of the ChargeCommand
<br>
- [ ] AC#3 Charges architecture diagram in GitHub has been updated to reflect this. 
- [ ] AC#4 [Contract documentation](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md) for charges and prices has been moved to protobuf contracts and page has been updated with links to the protobuf contracts
\* Limited to events fulfilling the charge data needs in the Aggregation domain.

**Comment by prtandrup** [comment]
**Description**:
With this story we implement the means to publish all events for charges and charges prices (to fulfill the charge data needs in the Aggregation domain).

**Tech notes:** 
- Events will be published to a ServiceBus in the Charges Domain.
- Protobuf is used.

**Preconditions:**
- Charges and charge prices events and contracts have been defined and documented by story #352 

**Acceptance criteria**
(Must be reformulated and written like Gherkin tests once the events have been defined in #352)
AC#1 Charge Events\* are publish to ServiceBus adhering to the defined protobuf contract
AC#2 Charge Prices Events\* are publish to ServiceBus adhering to the defined protobuf contract.
AC#3 Charges architecture diagram in GItHub has been updated to reflect this. 

* Limited to events fulfilling the charge data needs in the Aggregation domain.
