### ISSUE TITLE
Create Charge and charge links and distribute them to Grid companies 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-charges#498]
### Description 

Purpose of this feature is to create outbound messages from the charge domain and make them available for distribution, based on created charges and charge links. 

This feature focus solely on messages intended for the grid companies. 

The messages cover creation of tariffs, newly created metering points, and charge links.  Gather all needed data to create an RSM file of the types {RSM-031, RSM-034}, in CIM XML, to be fetched from the general postal office. 

A template version of a local postal is made available from team titans

### Acceptance Criteria

- [ ] A local postal office in the charge domain
- [ ]  All data needed for an RSM-034 message is handed to the local postal office, for tariffs 
- [ ]  All data needed for an RSM-031 message is handed to the local postal office, for charge links (including default charge link for created metering points)

### Estimate
5 man sprint.

**Comment by BjarkeMeier** [comment]
@PerTHenriksen, as far as I can tell the following would be the business equivalent ACs for this feature. Please read carefully as I'm definitely not sure I got it right...

(BRS-004)
Given the charges domain
When a grid access provider submits a new metering point
And the grid access provider subsequently peeks
Then the grid access provider receives a bundle with the CIM NotifyBillingMasterData_MarketDocument notification (RSM-031)
for each tax tarif linked to the metering point

(BRS-033)
Given the charges domain
When the TSO creates a tax tarif
And a grid access provider subsequently peeks
Then the grid access provider receives a bundle with a CIM NotifyPriceList_MarketDocument notification (RSM-034)

(BRS-033)
Given the charges domain
When the TSO stops a tax tarif
And a grid access provider subsequently peeks
Then the grid access provider receives a bundle with the CIM NotifyBillingMasterData_MarketDocument notification (RSM-031)

(BRS-037)
Given the charges domain
When an energy supplier submits a tax tarif
And a grid access provider subsequently peeks
Then the grid access provider receives a bundle with a CIM NotifyBillingMasterData_MarketDocument notification (RSM-031)
with a link to the tarif for each metering point with the given metering point type in the grid area

(BRS-037)
Given the charges domain
When TSO creates a tax tarif
And a grid access provider subsequently peeks
Then the grid access provider receives a bundle with a CIM NotifyBillingMasterData_MarketDocument notification (RSM-031)
with a link to the tarif for each metering point with the given metering point type in the grid area
