### ISSUE TITLE
Add domain test of post office peek

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#691]
** Synopsis **

As team Volt
We want good confidence that the charges domain always support actor peek of messages for created charge links
So that we always have a releasable domain/product

Please note that this is the first domain (black box) test of the charges domain. So it's expected to be a first-mover story fixing all the bumps on the road.

** Tech Notes **

It's all moving parts, but as of this writing the following is anticipated. Consider it helpful input rather than requirements.

- Post Office NuGet is not to be mocked, but queue name must be configurable (as discussed on dev session 11th of October)
- Post office functionality must be mocked. We assume the simplest way is to add a test-only function, that subscribes to the post office dataavailable queue and sends a peek request to the charges domain - Bjarke: This is probably not correct, I think we only would need the test function for our personal sandboxes if desired. Domain tests should not require or use such a function
- Dan recommends that:
Og jeg har tænkt mere over brug af ServiecBusListenerMock (Bjarke og jeg talte om det i fredags). Jeg er kommet frem til at det pt. er bedst at vi har en listener per eksterne queue/topic (dvs. dem jeres domæne sender til) som vi ønsker at "verify/asserte" på. Dvs. det du var i gang med Bjarke. 😊
Men i må ikke sætte listener op til at fange beskeder på jeres interne queues/topics, for så spiser de beskederne fra jeres functions. 
- Team has a agreed to put domain tests in separate test project
- We should probably use this story to move all db/repository integration tests to the integration test project

** Acceptance-Criteria **

AC 1:
Given the charges domain
When a (CIM XML) charge link creation message is received
And an actor eventually peeks
Then a bundle is sent to the Message Hub

AC 2:
Given the developer localhost setup documentation
When a developer wants to execute all XunitTest including the domain tests
He/she is able to do this by following the documentation

**Tasks**

- ~~[ ] Add setup documentation~~ (solved by @HenrikSommer)
- [x] Have Titans create test/simulation NuGet package for MessageHub behavior - [story](https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/336) created on their board
- ~~[ ] Create separate domain test project~~
- [x] Change from dataavailable to peek test
- ~~[ ] Move repository integration tests to integration test project~~ Superseeded by clean up structure task
- ~~[ ] Use UnitTest|IntegrationTest|DomainTest attributes?~~ Deemed not now due to uncertainty
- ~~[ ] Generalize MessageHub integration test code~~
- [x] Use EnvironmentSettingNames everywhere
- [x] Add Postman and peek and dequeue requests (for all environments)
- ~~[ ] Add integration test of data-available~~
- ~~[ ] Add integration test of peek~~
- [x] Clean up file/folder/project structure of all integration and domain tests (will do together with @prtandrup)

**Comment by prtandrup** [comment]
**AC#1:** 
- Domain test executed locally (see AC#2): ✅

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a5644cdd-5759-427a-af5b-ee6224adee76)
Note the number of tests = 23, needed to verify below:

- Domain test executed as part of FunctionHost CI [run](https://github.com/Energinet-DataHub/geh-charges/runs/4093223228?check_suite_focus=true): ✅

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a029b432-9db7-4b9b-bc87-d370b247c770)

**AC#2:** Ran the domain test from localhost (followed the [documentation](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/local-development/README.md))

**Comment by prtandrup** [comment]
Bug #788 has been fixed and tested OK (see my closing [comment](https://github.com/Energinet-DataHub/geh-charges/issues/788#issuecomment-973860591))
The same comment applies here as well.
This story has been through PO acceptance, hence Closed.
