### ISSUE TITLE
Deliver mocked charge links data to Frontend for a single (consumption) metering point

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#792]
**Synopsis:**
Upon searching and viewing a single consumption metering point in a Graphical User Interface (GUI), the Charges domain must be able to provide charge links data associated with that metering point (a viewer could be a Grid Access Provider, an Electricity Supplier, Support line, etc.)

A GUI user is expected to search and view a single metering and within that screen a simplistic overview of the charge links associated with the given metering point are displayed.

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/b3c2d7d8-c447-403f-82c9-28bfc826e664)

**Tech notes**
* Volt: Expose API to BFF (Backend For Frontend)
* Volt: Expose API to Frontend from BFF, accessible through swagger UI
* The charge links data served will be mocked. A later story will link actual charge links data from storage to frontend (#827)
* The data served to the frontend is documented
* Thomas from team Batman has already made a similar solution for GetMeteringPointByGsrn, example can be found [here](https://github.com/Energinet-DataHub/greenforce-frontend/tree/main/apps/dh/api-dh)
* For any BFF assistance, please reach out to Dan (Mighty Ducks)
* Alexander (Mighty Ducks) is the initial consumer of this.

**Out of scope:**
* Charge Links for other types of Metering Points than consumption
* Auth / data access rights to charge links data
* Pagination support is not required as the max amount of charge links per type per metering point is expected to be 15 (rare cases).

**Acceptance criteria:**

1.  - [ ] 
Given a consumption metering point
When a request for charge links data for that specific metering point is made (at the BFF)
Then the response contains all the mocked charge links for that given metering point
<br>

2.  - [ ]
Given a valid request for charge links data is processed
When responding
The response contains the following data for a charge link:

* Charge Type
* Charge Id (aka SenderProvidedChargeId)
* Charge Name
* Charge Owner Id
* Charge Owner Name
* Tax or TaxIndicator (Only relevant for Tariff links)
* TransparentInvoicing
* Factor (or Quantity) - Only relevant for Fee and Subscription links)
* StartDateTimeUtc (or Valid From)
* EndDateTimeUtc (or Valid To) - OBS: if set to max/infinite in the data model - we will return null)

3.  - [ ] 
Given a consumption metering point with ZERO charge links
When a request is made
Then the response returned is 404 not found

<hr>

**Task list:**
_Backend work:_ 
- [x] Web API that delivers mocked charge links json data + unit test + integration test
- [x] Set up Postman requests against backend API
- [x] Use shared ChargeLinkDto.cs in backend Web API and align controller method name (GetAsync) ([PR](https://github.com/Energinet-DataHub/geh-charges/pull/914))

_Nuget packages:_
~~- [ ] Create and publish Clients.Bff ([PR](https://github.com/Energinet-DataHub/geh-charges/pull/882))~~
~~- [ ] Create and publish Clients.Abstractions ([PR](https://github.com/Energinet-DataHub/geh-charges/pull/882))~~
- [x] Change Package name `.Clients.SimpleInjector` to `.Clients.Registration` ([PR](https://github.com/Energinet-DataHub/geh-charges/pull/899))
- [x] Add `ChargelinksClient` to `.Clients` ([PR](https://github.com/Energinet-DataHub/geh-charges/pull/903))
- [x] Extend `.Clients.Registration` with `AddChargeLinksClient` ([PR](https://github.com/Energinet-DataHub/geh-charges/pull/903))

_BFF work:_
- [x] Add ChargeLinksController to Bff (use nuget packages: `.Clients` and `.Clients.Registration`) ([PR](https://github.com/Energinet-DataHub/greenforce-frontend/pull/192))
- [x] Tests ([PR](https://github.com/Energinet-DataHub/greenforce-frontend/pull/192))

**Comment by prtandrup** [comment]
I've asked for confirmation from PM that AUTH/data access rights is out of scope for this story.

**Comment by prtandrup** [comment]
At iteration planning, the decided to do a vertical slice of this story so instead of delivering actual charge links data for a single metering point from storage, we will be serving mocked data. A later story #827 will replace the mock data with actual data.

**Comment by prtandrup** [comment]
Blocked due to architectural considerations.

**Comment by prtandrup** [comment]
I closed pull request (882) as a team decision has been made (Bjarke, Lasse and I) to move the content of .Bff into .Clients and the content of .Abstractions: ChargeLinkDTO.cs and ChargeType.cs will be shared the same way as we share .proto file between backend and client package; through Energinet.DataHub.Contracts.

I'll refactor this and create a new PR.
Btw, it's no longer blocked :smiley:

**Comment by prtandrup** [comment]
#### For the tester:

⚠️ **BFF only works in U-001** ⚠️

In `Postman > Charges Domain workspace > Samples Collection` you'll find a folder for 
`BackendForFrontEnd (BFF)` in which the needed requests are located:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/217b82d2-9a7a-4542-9f89-ed51c9e9a25e)

**Comment by Mech0z** [comment]
AC1:
Tested with "valid" MP on U-001
![image](https://user-images.githubusercontent.com/2316684/146198629-0e63c30f-fba4-4bc3-b03a-bda1f171b36f.png)

AC2:
Names look correct, there are some updates as https://github.com/Energinet-DataHub/geh-charges/issues/933 have updated some names

Therefor 
-     ChargeOwnerId => ChargeOwner
-     Factor (or Quantity) => Quantity
-     StartDateTimeUtc => StartDate
-     EndDateTimeUtc => EndDate

AC:3
Tested with MP which does not exist
![image](https://user-images.githubusercontent.com/2316684/146198732-54aaa3dc-5c98-43a5-adf9-263faa5dfcb7.png)
