### ISSUE TITLE
Deliver charge links data from data storage to Frontend (replacing mock data)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#827]
**Synopsis:**
In story #792 we enabled the backend to serve mocked charge links data for a single metering point to the frontend (through the BFF).
With this story we'll replace the mocked data with actual charge links data from our data storage. 

**Tech notes:**
Actual charge links (minus historical/inactive) for a metering point is delivered to frontend
~~Does not require CQRS~~ Yes it does unless we want more future refactoring work.

**Acceptance criteria**
- [ ] Given a new Consumption metering point is created and default charges have been linked to it
When looking at the metering point in the front end
Then the "Priser" tab shows displays the default charge links.

- [ ] Given a consumption metering point exist
When the System Operator creates a new charge link to one of its' charges 
Then afterwards the new charge link will be visible in the front end.

~~- [ ] Charge Links are also delivered for Child MPs~~ Not possible to test until Special MPs are persisted in Charges database. Not intended to be blocking this story.

**Task list**
- [x] Deliver actual charge link data from storage via new query stack [[PR](https://github.com/Energinet-DataHub/geh-charges/pull/768)]
- [x] Add ChargeLinksController integration tests
~~- [ ] Update EF Core to 6.0 in the Charges Web API project~~ 
~~- [ ] Add ChargeLinksController unit tests~~
- [x] Wire Charges Web API up with Application Insights [[PR](https://github.com/Energinet-DataHub/geh-charges/pull/1032)]

- [x] Consider using `--no-onconfiguring` in scaffold script to avoid creating OnConfiguring in QueryDbContext, [link](https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-dbcontext-scaffold)
- [x] Remember to remove useNodaTime
- [x] Handle enddates set to max. Last three bullets are located in this [[PR](https://github.com/Energinet-DataHub/geh-charges/pull/1036)].

**Comment by lasrinnil** [comment]
After researching at what cost and the surrounding issues with being able to unittest our QueryDBContext / IQuerable. At the moment we have decided this is not the time, perhaps in the future if MS moves EFCore in a direction that makes more sense to unittest.

**Comment by prtandrup** [comment]
As we cannot test the AC regarding 'displaying charge links in front end for Child MPs (special MPs)' because it requires #936 to be completed, I've decided to remove it here and add it to #936.

**Comment by prtandrup** [comment]
For the tester..
Please reach out to me for details on how to test this, e.g. frontend URL, creating a frontend user, etc.

**Comment by prtandrup** [comment]
Currently blocked, as an issue stops us from linking a charge to a metering point. U-001

**Comment by prtandrup** [comment]
Blocked tag removed; its now possible to link a charge to a newly created consumption mp

**Comment by PerTHenriksen** [comment]
Test runbook (and demo agenda) Part 1 of 2

# Opret bruger til U-001 frontenden:

Opret bruger (spørg teamet for link)
Frontend url (spørg teamet for link)



# Opret forbrugsmålepunkt



1) I Postman, skift til metering point workspaces
2) Kontroller at du sender til på "Dev-001"
3) I folderen 'CreateMP' brug requesten 'CreateSingleConsumptionMP' til at oprette et nyt forbrugsmålepunkt
4) Brug Peek og Dequeue i 'PeekDequeue' folderen indtil du får en Confirm på målepunktsoprettelse (hvilket trigger default charge links flowet
(besked til målepunktsoprettelse i næste opslag)


# AC1: Fremsøg målepunkt i frontenden og kontroller at du får følgende default charge links vist, under Priser tab'en:
40000
41000
45013
EA-001



# AC2: Tilføj et ny charge link til det nyoprettede målepunkt



Brug charge id: EA-003,
type: D03,
dato: 2022-02-28T23:00:00Z,
ejer: 5790000432752
Husk at tilføje dit nye målepunkt til beskeden
(Peek/dequeue optional)


Og fremsøg målepunktet igen i frontenden, hvor du gerne skulle se det nye link.

**Comment by PerTHenriksen** [comment]
Test runbook (and demo agenda) part 2 of 2
Below is an adjusted message for creation of a new consumption metering point, as the template in postman is shared for editing:

<cim:RequestChangeAccountingPointCharacteristics_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeaccountingpointcharacteristics:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeaccountingpointcharacteristics:0:1 urn-ediel-org-structure-requestchangeaccountingpointcharacteristics-0-1.xsd">
<cim:mRID>253698245</cim:mRID>
<cim:type>E58</cim:type>
<cim:process.processType>E02</cim:process.processType>
<cim:businessSector.type>23</cim:businessSector.type>
<cim:sender_MarketParticipant.mRID codingScheme="A10">8200000001409</cim:sender_MarketParticipant.mRID>
<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
<cim:receiver_MarketParticipant.mRID codingScheme="A10">DHGLN</cim:receiver_MarketParticipant.mRID>
<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
<cim:createdDateTime>2021-06-17T09:30:47Z</cim:createdDateTime>
<cim:MktActivityRecord>
<cim:mRID>{{transactionId}}</cim:mRID>
<cim:businessProcessReference_MktActivityRecord.mRID>String</cim:businessProcessReference_MktActivityRecord.mRID>
<cim:validityStart_DateAndOrTime.dateTime>2021-09-25T22:00:00Z</cim:validityStart_DateAndOrTime.dateTime>
<cim:MarketEvaluationPoint>
<cim:mRID codingScheme="A10">{{gsrn}}</cim:mRID>
<cim:type>E17</cim:type>
<cim:settlementMethod>E02</cim:settlementMethod>
<cim:meteringMethod>D02</cim:meteringMethod>
<cim:connectionState>D03</cim:connectionState>
<cim:readCycle>PT1H</cim:readCycle>
<cim:netSettlementGroup>6</cim:netSettlementGroup>
<cim:nextReadingDate>--12-01</cim:nextReadingDate>
<cim:meteringGridArea_Domain.mRID codingScheme="NDK">870</cim:meteringGridArea_Domain.mRID>
<cim:linked_MarketEvaluationPoint.mRID codingScheme="A10">575774240560385464</cim:linked_MarketEvaluationPoint.mRID>
<cim:physicalConnectionCapacity unit="KWT">6000</cim:physicalConnectionCapacity>
<cim:mPConnectionType>D02</cim:mPConnectionType>
<cim:disconnectionMethod>D01</cim:disconnectionMethod>
<cim:asset_MktPSRType.psrType>D12</cim:asset_MktPSRType.psrType>
<cim:productionObligation>false</cim:productionObligation>
<cim:contractedConnectionCapacity unit="KWT">230</cim:contractedConnectionCapacity>
<cim:ratedCurrent unit="AMP">32</cim:ratedCurrent>
<cim:Series>
<cim:product>8716867000030</cim:product>
<cim:estimatedAnnualVolume_Quantity.quantity>0</cim:estimatedAnnualVolume_Quantity.quantity>
<cim:quantity_Measure_Unit.name>KWH</cim:quantity_Measure_Unit.name>
</cim:Series>
<cim:description>String</cim:description>
<cim:usagePointLocation.geoInfoReference>0a3f50b9-b942-32b8-e044-0003ba298018</cim:usagePointLocation.geoInfoReference>
<cim:usagePointLocation.mainAddress>
<cim:streetDetail>
<cim:code>0405</cim:code>
<cim:name>Vestergade</cim:name>
<cim:number>10</cim:number>
<cim:floorIdentification>1</cim:floorIdentification>
<cim:suiteNumber>12</cim:suiteNumber>
</cim:streetDetail>
<cim:townDetail>
<cim:code>0625</cim:code>
<cim:name>Middelfart</cim:name>
<cim:section>Strib</cim:section>
<cim:country>DK</cim:country>
</cim:townDetail>
<cim:postalCode>5500</cim:postalCode>
</cim:usagePointLocation.mainAddress>
<cim:usagePointLocation.actualAddressIndicator>true</cim:usagePointLocation.actualAddressIndicator>
<cim:parent_MarketEvaluationPoint.mRID codingScheme="A10"></cim:parent_MarketEvaluationPoint.mRID>
</cim:MarketEvaluationPoint>
</cim:MktActivityRecord>
</cim:RequestChangeAccountingPointCharacteristics_MarketDocument>

**Comment by PerTHenriksen** [comment]
Storied tested succesfully:
![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/e1fdcf43-0b03-42bf-8d1c-2a5a7bf549a6)
