### ISSUE TITLE
Use actor and grid area register to ensure actors only receive relevant messages for Charge Links

### ISSUE THREAD

**Issue by HenrikSommer** [Energinet-DataHub/geh-charges#926]
**Synopsis**
We need to ensure that grid operators only receive messages for Charge Links that are relevant to them.

**Acceptance criteria**

AC 1:
As a grid operator,
I want to receive all information intended for me
so that I can maintain charge links* in my local system,
(edit: actor register and grid area knowledge is required)

(*including default charge links from the BRS004 flow)

**Comment by BjarkeMeier** [comment]
Blocked for the same reasons as #924.

**Comment by BjarkeMeier** [comment]
**Tasks**
- [ ] Use separate market participant models (per role)?
- [ ] Clean up / split market participant repository?
- [ ] Fix all missing builder.Property(x => x.Id).ValueNeverGenerated();
- [ ] Fix sonar cloud warnings

**Comment by prtandrup** [comment]
### Tested ✅ in U-001 ... due to an auth issue in T-001.

<hr> 

**Test 1**
As a Grid Access Provider, 
(1) Create new consumption metering point
(2) Verify that you receive a charge links notification (with charge EA-001)
(3) Verify in some way, that there is no notification messages made available to other Grid Access Providers

<hr> 

Consumption MP ID: `572703444875823586`

Notification message:
````
<?xml version="1.0" encoding="utf-8"?>
<cim:NotifyBillingMasterData_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:notifybillingmasterdata:0:1" xsi:schemaLocation="urn:ediel.org:structure:notifybillingmasterdata:0:1 urn-ediel-org-structure-notifybillingmasterdata-0-1.xsd">
    <cim:mRID>d94b4cddb6f848129e124b0ff1dd98b3</cim:mRID>
    <cim:type>D07</cim:type>
    <cim:process.processType>D17</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">9656626091925</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-02-04T10:03:32Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>036793c259a9425faf8c0d2520c31888</cim:mRID>
        <cim:marketEvaluationPoint.mRID codingScheme="A10">572703444875823586</cim:marketEvaluationPoint.mRID>
        <cim:start_DateAndOrTime.dateTime>2021-12-31T23:00:00Z</cim:start_DateAndOrTime.dateTime>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>EA-001</cim:mRID>
                <cim:factor>1</cim:factor>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:NotifyBillingMasterData_MarketDocument>
````

Only one grid access provider is notified (the one creating the metering point), shown through a database look-up:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/9ad2ce40-c8c0-4ae3-b882-81df98d0fa10)

<hr> 

**Test 2**
As a Grid Access Provider
(1) Create a charge link with a tax tariff (owned by the Grid Access Provider*)
(2) Verify that the Grid Access Provider is the only one to receive a **charge link confirmation**
(3) Verify that the Grid Access Provider is the only one to receive a **charge link notification**

_*Disclaimer: Due to our current Auth/test organisations setup, this test is not business-wise valid, as the charge link would be done either by the System Operator or the Electricity Supplier - with a tax tariff owned by the System Operator._ 

<hr> 

Tax Tariff ID: ChgId001

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/6f1edf7f-2710-4835-91df-4abf8f566d85)

(1) Create charge Link request:

````
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2021 rel. 3 (x64) (http://www.altova.com)-->
<cim:RequestChangeBillingMasterData_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangebillingmasterdata:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangebillingmasterdata:0:1 urn-ediel-org-structure-requestchangebillingmasterdata-0-1.xsd">
	<cim:mRID>DocId2022-02-04T10:13:30.700Z</cim:mRID>
	<cim:type>D05</cim:type>
	<cim:process.processType>D17</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">9656626091925</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="NCS">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-02-04T11:13:30Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>clId2022-02-04T10:13:30.700Z</cim:mRID>
		<!--cim:businessProcessReference_MktActivityRecord.mRID>String</cim:businessProcessReference_MktActivityRecord.mRID-->
		<cim:marketEvaluationPoint.mRID codingScheme="NRO">572703444875823586</cim:marketEvaluationPoint.mRID>
		<cim:start_DateAndOrTime.dateTime>2022-12-31T23:00:00Z</cim:start_DateAndOrTime.dateTime>
		<cim:chargeGroup.chargeType.chargeTypeOwner_MarketParticipant.mRID codingScheme="NFI">9656626091925</cim:chargeGroup.chargeType.chargeTypeOwner_MarketParticipant.mRID>
		<cim:chargeGroup.chargeType.type>D03</cim:chargeGroup.chargeType.type>
		<cim:chargeGroup.chargeType.mRID>ChgId001</cim:chargeGroup.chargeType.mRID>
		<cim:chargeGroup.chargeType.factor>1</cim:chargeGroup.chargeType.factor>
	</cim:MktActivityRecord>
</cim:RequestChangeBillingMasterData_MarketDocument>

````

(2) Receive confirmation + show only one grid access provider gets a notification:

````
<?xml version="1.0" encoding="utf-8"?>
<cim:ConfirmRequestChangeBillingMasterData_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:confirmrequestchangebillingmasterdata:0:1" xsi:schemaLocation="urn:ediel.org:structure:confirmrequestchangebillingmasterdata:0:1 urn-ediel-org-structure-confirmrequestchangebillingmasterdata-0-1.xsd">
    <cim:mRID>bd2c262762fd4844a5f9d8377a5e49ea</cim:mRID>
    <cim:type>D06</cim:type>
    <cim:process.processType>D17</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">9656626091925</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-02-04T10:14:29Z</cim:createdDateTime>
    <cim:reason.code>A01</cim:reason.code>
    <cim:MktActivityRecord>
        <cim:mRID>9e17652bb1e34041afbe29310c113029</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>clId2022-02-04T10:13:30.700Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
        <cim:marketEvaluationPoint.mRID codingScheme="A10">572703444875823586</cim:marketEvaluationPoint.mRID>
    </cim:MktActivityRecord>
</cim:ConfirmRequestChangeBillingMasterData_MarketDocument>
````

Database look-up shows confirmation is only sent to one grid access provider; the one creating the link:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a5d0c489-e96b-47cd-909a-83fbf289bf70)

(3) Receive charge link notification + verify it is only sent to one grid access provider; the one owning the metering point:

````
<?xml version="1.0" encoding="utf-8"?>
<cim:NotifyBillingMasterData_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:notifybillingmasterdata:0:1" xsi:schemaLocation="urn:ediel.org:structure:notifybillingmasterdata:0:1 urn-ediel-org-structure-notifybillingmasterdata-0-1.xsd">
    <cim:mRID>b49e80a8c6ab468fb2b5cb5d48f3400a</cim:mRID>
    <cim:type>D07</cim:type>
    <cim:process.processType>D17</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">9656626091925</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-02-04T10:17:57Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>1044a34df83048a68dd5b51863abbf07</cim:mRID>
        <cim:marketEvaluationPoint.mRID codingScheme="A10">572703444875823586</cim:marketEvaluationPoint.mRID>
        <cim:start_DateAndOrTime.dateTime>2022-12-31T23:00:00Z</cim:start_DateAndOrTime.dateTime>
        <cim:end_DateAndOrTime.dateTime>1970-01-01T00:00:00Z</cim:end_DateAndOrTime.dateTime>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">9656626091925</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>ChgId001</cim:mRID>
                <cim:factor>1</cim:factor>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:NotifyBillingMasterData_MarketDocument>
````
Database look-up shows notification is only sent to one grid access provider; the one creating the link:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/efe473bc-df2a-4187-9d14-dbb431af68f7)
